### ISSUE TITLE
How to hide/unpublish content

### ISSUE THREAD

**Issue by andrewshell** [scripting/oldSchoolBlog#4]
I have some content on my blog that I'd like to keep in my outline, but not publish to the web.

Maybe that's draft content that I'm working on, or something that hasn't aged well.

**What I did:**

Clicked the + button to create a new note.
Added some text
Pressed Command-\ to turn it into a comment
Waited for outline to save
Published with Old School

**What I expected:**

I expected that the commented out note would not appear on the website.

**What happened:**

It was published exactly the same as if it wasn't commented.

**Comment by scripting** [comment]
This is an excellent bug report. Thanks.

**Comment by andrewshell** [comment]
This works as expected now. 😄
